---
title: "Analisis matriz de correlacion Capacidad estatal"
autor: "Nicolas Aristizabal"
output: html_document
date: "2025-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#instalacion de paquetes necesarios
library(corrplot)
library(haven)
library(dplyr)

#leer datos .dta en R
datos_c <- read_dta("C:/Users/nikko/OneDrive/Documents/Semillero R/CAPACIDAD-ESTATAL/Paquete Rep. Nat/Final/main_data_candidate_level.dta")
datos_m <- read_dta("C:/Users/nikko/OneDrive/Documents/Semillero R/CAPACIDAD-ESTATAL/Paquete Rep. Nat/Final/main_data_municipal_level.dta")

```

# Introduccion

aca se pondra el analisis de la matriz de correlacion de capacidad estatal

```{r}
#Tabla de correlaciones entre las variables medidas para compra de votos
correlaciones <- cor(datos_m[, c("z_likelihood_misdeed_1", 
                               "z_likelihood_misdeed_2",
                               "z_likelihood_misdeed_3",
                               "z_likelihood_misdeed_4",
                               "z_likelihood_misdeed_5",
                               "z_likelihood_misdeed_6")],
                     use = "complete.obs")  

#Tabla de correlaciones entre las variables medidas para compra de votos
nombres <- c("intimidación de votantes", 
                            "compra de votos", 
                            "fraude de registro",
                            "fraude electoral", 
                            "campaña de servidores públicos", 
                            "publicidad ilícita")


# Cambiar nombres de columnas Y filas
colnames(correlaciones) <- nombres
rownames(correlaciones) <- nombres

# Visualizar la matriz de correlaciones
corrplot(correlaciones, method = "color", type = "upper", 
         addCoef.col = "black", 
         tl.col = "black",      
         tl.srt = 45)            


```

